image: node:8.12.0

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install unzip zip
          - zip -r iis.zip ./*
          - ls -l
          - curl -u ${user}:${build} -X POST https://api.bitbucket.org/2.0/repositories/mivp/iis/downloads -F files=@iis.zip
