CREATE TABLE Baugruppen (
  Bezeichnung TEXT,
  Baugruppennummer TEXT,
  Artikelnummer TEXT,
  CADDatei BLOB,
  PRIMARY KEY (Baugruppennummer)
);

CREATE TABLE Teile (
  Bezeichnung TEXT,
  Teilnummer TEXT,
  Artikelnummer TEXT,
  CADDatei BLOB,
  PRIMARY KEY (Teilnummer)
);

CREATE TABLE TeileEinbau (
  Teil TEXT REFERENCES Teile(Teilnummer),
  Baugruppe TEXT REFERENCES Baugruppen(Baugruppennummer),
  Einbauanweisung TEXT
);

CREATE TABLE BaugruppenEinbau (
  Unterbaugruppe TEXT REFERENCES Baugruppen(Baugruppennummer),
  Überbaugruppe TEXT REFERENCES Baugruppen(Baugruppennummer),
  Einbauanweisung TEXT
);

CREATE TABLE Fertigungsdaten (
  Artikelnummer TEXT,
  Bearbeitungsdauer NUMERIC,
  Zeitstempel DATETIME
);

INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('3D Drucker', '', 'MendelMax 1.5 komplett');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0113/A', '0113', 'Strangpressprofil 300mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0113/A', '3D Drucker');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0113/A', '3D Drucker');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0113/A', '3D Drucker');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0113/A', '3D Drucker');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0027/A', '0027', 'Unterer linker Rahmenverbinder inkl. Schrauben und Nutensteine');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0027/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0027/A', '3D Drucker');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0117/A', '0117', 'Unterer linker Rahmenverbinder');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0117/A', 'B0027/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0028/A', '0028', 'ISK-Schraube M5x10 + Scheibe');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0027/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0027/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0027/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0027/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0027/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0027/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0027/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0027/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0027/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0027/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0079/A', '0079', 'Innensechskantschraube M5x10mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0079/A', 'B0028/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0121/A', '0121', 'Scheibe M5');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0121/A', 'B0028/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0099/A', '0099', 'Nutenstein M5');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0027/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0027/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0027/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0027/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0027/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0027/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0027/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0027/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0029/A', '0029', 'Unterer rechter Rahmenverbinder inkl. Schrauben und Nutensteine');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0029/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0029/A', '3D Drucker');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0118/A', '0118', 'Unterer rechter Rahmenverbinder');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0118/A', 'B0029/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0029/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0029/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0029/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0029/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0029/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0029/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0029/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0029/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0029/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0029/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0029/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0029/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0029/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0029/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0029/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0029/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0029/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0029/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0116/A', '0116', 'Strangpressprofil 420mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0116/A', '3D Drucker');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0116/A', '3D Drucker');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0116/A', '3D Drucker');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0116/A', '3D Drucker');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0114/A', '0114', 'Strangpressprofil 340mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0114/A', '3D Drucker');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0114/A', '3D Drucker');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0114/A', '3D Drucker');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0114/A', '3D Drucker');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0115/A', '0115', 'Strangpressprofil 420mm gebohrt');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0115/A', '3D Drucker');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0115/A', '3D Drucker');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0031/A', '0031', 'Oberer Rahmenverbinder rechts inkl. Schrauben und Nutensteine');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0031/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0031/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0031/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0031/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0031/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0031/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0031/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0031/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0031/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0031/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0031/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0031/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0101/A', '0101', 'Oberer Rahmenverbinder');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0101/A', 'B0031/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0030/A', '0030', 'Flachkopfschraube M5 und Scheibe');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0030/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0030/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0030/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0030/A', '3D Drucker');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0121/A', 'B0030/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0065/A', '0065', 'Flachkopfschraube mit Innensechskant M5x30mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0065/A', 'B0030/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0032/A', '0032', 'Rahmenverbinder Z-Achse Zusammenbau');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0032/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0032/A', '3D Drucker');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0106/A', '0106', 'Rahmenverbinder Z-Achse');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0106/A', 'B0032/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0032/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0032/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0105/A', '0105', 'Radialrillenkugellager 608ZZ');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0105/A', 'B0032/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0032/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0032/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0110/A', '0110', 'Sechskantmutter M8');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0110/A', 'B0032/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0110/A', 'B0032/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0103/A', '0103', 'Praezisionswelle 8mm x 350mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0103/A', '3D Drucker');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0103/A', '3D Drucker');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0033/A', '0033', 'Motorhalter Z-Achse Zusammenbau');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0033/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0033/A', '3D Drucker');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0094/A', '0094', 'Motorhalter Z-Achse');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0094/A', 'B0033/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0033/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0033/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0033/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0033/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0033/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0033/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0033/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0033/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0097/A', '0097', 'NEMA 17 Schrittmotor');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0097/A', 'B0033/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0034/A', '0034', 'ISK-Schraube M3x10 + Scheibe');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0034/A', 'B0033/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0034/A', 'B0033/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0034/A', 'B0033/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0034/A', 'B0033/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0119/A', '0119', 'Scheibe M3');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0119/A', 'B0034/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0072/A', '0072', 'Innensechskantschraube M3x10mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0072/A', 'B0034/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0079/A', 'B0033/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0079/A', 'B0033/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0109/A', '0109', 'Sechskantmutter M5 flach');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0109/A', 'B0033/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0109/A', 'B0033/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0083/A', '0083', 'Klemmvorrichtung');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0083/A', 'B0033/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0095/A', '0095', 'Motorkupplung Z-Achse');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0095/A', 'B0033/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0068/A', '0068', 'Gewindestange M8x325mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0068/A', '3D Drucker');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0068/A', '3D Drucker');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0035/A', '0035', 'Spannrollenhalter Y-Achse Zusammenbau');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0035/A', '3D Drucker');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0122/A', '0122', 'Scheibe M8 gross');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0122/A', 'B0035/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0122/A', 'B0035/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0036/A', '0036', 'Spannrollenhalter Y-Achse inkl. Schrauben und Nutensteine');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0036/A', 'B0035/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0036/A', 'B0035/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0036/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0036/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0036/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0036/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0111/A', '0111', 'Spannrollenhalter Y-Achse');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0111/A', 'B0036/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0110/A', 'B0035/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0110/A', 'B0035/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0067/A', '0067', 'Gewindestange M8x55mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0067/A', 'B0035/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0105/A', 'B0035/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0105/A', 'B0035/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0037/A', '0037', 'Motorhalter Y-Achse Zusammenbau');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0037/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0034/A', 'B0037/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0034/A', 'B0037/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0097/A', 'B0037/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0096/A', '0096', 'Motorritzel T2,5');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0096/A', 'B0037/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0079/A', 'B0037/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0079/A', 'B0037/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0093/A', '0093', 'Motorhalter Y-Achse');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0093/A', 'B0037/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0037/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0037/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0048/A', '0048', 'Y-Achse');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0048/A', '3D Drucker');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0047/A', '0047', 'Druckbett Zusammenbau');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0047/A', 'B0048/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0090/A', '0090', 'MDF-Platte klein');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0090/A', 'B0047/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0040/A', '0040', 'Lageraufnahme LM8UU Zusammenbau');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0040/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0040/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0040/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0040/A', 'B0047/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0107/A', '0107', 'Sechskantmutter M3');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0040/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0084/A', '0084', 'Lageraufnahme LM8UU');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0084/A', 'B0040/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0081/A', '0081', 'Kabelbinder Lageraufnahme');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0081/A', 'B0040/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0081/A', 'B0040/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0041/A', '0041', 'ISK-Schraube M3x9mm (gek�rzt) und Scheibe');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0041/A', 'B0040/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0119/A', 'B0041/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0071/A', '0071', 'Innensechskantschraube M3x9mm (gekuerzt)');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0071/A', 'B0041/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0085/A', '0085', 'Linearkugellager LM8UU');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0085/A', 'B0040/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0056/A', '0056', 'Druckbettfeder Innendurchmesser 5,3mm x 30mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0056/A', 'B0047/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0056/A', 'B0047/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0056/A', 'B0047/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0056/A', 'B0047/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0089/A', '0089', 'MDF-Platte gross');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0089/A', 'B0047/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0042/A', '0042', 'Zahnriemenspanner Zusammenbau');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0042/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0042/A', 'B0047/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0119/A', 'B0042/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0119/A', 'B0042/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0073/A', '0073', 'Innensechskantschraube M3x20mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0073/A', 'B0042/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0127/A', '0127', 'Zahnriemenspanner gross');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0127/A', 'B0042/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0042/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0042/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0042/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0129/A', '0129', 'Zahnriemenspanner klein');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0129/A', 'B0042/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0043/A', '0043', 'B0043');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0043/A', 'B0042/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0043/A', 'B0042/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0119/A', 'B0043/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0074/A', '0074', 'Innensechskantschraube M3x25mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0074/A', 'B0043/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0044/A', '0044', 'ISK-Schraube M3x40mm und Scheibe');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0044/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0044/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0044/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0044/A', 'B0047/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0076/A', '0076', 'Innensechskantschraube M3x40mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0076/A', 'B0044/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0119/A', 'B0044/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0045/A', '0045', 'Sechskantmutter M3 und Scheibe');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0047/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0119/A', 'B0045/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0045/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0046/A', '0046', 'ISK-Schraube M3x30mm und Scheibe');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0046/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0046/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0046/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0046/A', 'B0047/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0119/A', 'B0046/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0075/A', '0075', 'Innensechskantschraube M3x30mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0075/A', 'B0046/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0070/A', '0070', 'Heizbett MK2A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0070/A', 'B0047/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0066/A', '0066', 'Foldback Klammer');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0066/A', 'B0047/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0066/A', 'B0047/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0066/A', 'B0047/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0066/A', 'B0047/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0053/A', '0053', 'Blechfaehnchen Y-Achse');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0053/A', 'B0047/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0055/A', '0055', 'Druckbett');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0055/A', 'B0047/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0034/A', 'B0047/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0038/A', '0038', 'Aufnahme 8mm-Achsen Zusammenbau');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0038/A', 'B0048/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0104/A', '0104', 'Praezisionswelle 8mm x 420mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0104/A', 'B0038/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0104/A', 'B0038/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0039/A', '0039', 'Aufnahme 8mm-Achsen inkl. Schrauben und Nutensteine');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0039/A', 'B0038/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0039/A', 'B0038/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0039/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0039/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0039/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0039/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0073/A', 'B0039/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0073/A', 'B0039/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0039/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0039/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0051/A', '0051', 'Aufnahme 8mm Achsen');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0051/A', 'B0039/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0125/A', '0125', 'Zahnriemen Y-Achse');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0125/A', '3D Drucker');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0054/A', '0054', 'X-Achse');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0054/A', '3D Drucker');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0124/A', '0124', 'Zahnriemen X-Achse');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0124/A', 'B0054/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0051/A', '0051', 'B0051');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0051/A', 'B0054/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0051/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0051/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0051/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0051/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0110/A', 'B0051/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0110/A', 'B0051/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0073/A', 'B0051/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0073/A', 'B0051/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0092/A', '0092', 'Motorhalter X-Achse');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0092/A', 'B0051/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0051/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0085/A', 'B0051/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0085/A', 'B0051/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0072/A', 'B0051/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0072/A', 'B0051/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0072/A', 'B0051/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0096/A', 'B0051/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0049/A', '0049', 'ISK-Schraube M3x20mm mit Scheibe');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0049/A', 'B0051/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0049/A', 'B0051/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0119/A', 'B0049/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0073/A', 'B0049/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0097/A', 'B0051/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0054/A', '0054', 'Blechfaehnchen Z-Achse');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0054/A', 'B0051/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0063/A', '0063', 'Feder Z-Achse Innendurchmesser 8,2mm x 30mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0063/A', 'B0051/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0050/A', '0050', 'Gewindestangenaufnahme');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0050/A', 'B0054/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0110/A', 'B0050/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0110/A', 'B0050/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0110/A', 'B0050/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0110/A', 'B0050/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0105/A', 'B0050/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0105/A', 'B0050/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0067/A', 'B0050/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0123/A', '0123', 'Scheibe M8');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0123/A', 'B0050/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0123/A', 'B0050/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0122/A', 'B0050/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0122/A', 'B0050/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0085/A', 'B0050/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0085/A', 'B0050/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0063/A', 'B0050/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0050/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0050/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0050/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0050/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0049/A', 'B0050/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0049/A', 'B0050/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0069/A', '0069', 'Gewindestangenaufnahme X-Achse');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0069/A', 'B0050/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0073/A', 'B0050/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0073/A', 'B0050/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0102/A', '0102', 'Praezisionswelle 8mm x 450mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0102/A', 'B0054/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0102/A', 'B0054/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0052/A', '0052', 'Schlitten X-Achse Zusammenbau');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0052/A', 'B0054/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0073/A', 'B0052/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0073/A', 'B0052/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0073/A', 'B0052/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0073/A', 'B0052/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0073/A', 'B0052/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0085/A', 'B0052/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0085/A', 'B0052/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0085/A', 'B0052/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0085/A', 'B0052/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0043/A', 'B0052/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0043/A', 'B0052/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0043/A', 'B0052/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0043/A', 'B0052/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0052/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0052/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0052/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0052/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0052/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0086/A', '0086', 'Schlitten X-Achse (Linearkugellageraufnahme X-Achse)');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0086/A', 'B0052/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0052/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0052/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0052/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0052/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0052/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0126/A', '0126', 'Zahnriemenspanner gross X-Achse');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0126/A', 'B0052/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0128/A', '0128', 'Zahnriemenspanner klein X-Achse');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0128/A', 'B0052/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0128/A', 'B0052/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0052/A', '0052', 'Blechfaehnchen X-Achse');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0052/A', 'B0052/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0072/A', 'B0052/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0053/A', '0053', 'ISK-Schraube M4x20mm mit Scheibe');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0053/A', 'B0052/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0053/A', 'B0052/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0120/A', '0120', 'Unterlegscheibe M4');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0120/A', 'B0053/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0078/A', '0078', 'Innensechskantschraube M4x20mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0078/A', 'B0053/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0049/A', 'B0052/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0055/A', '0055', 'Netzteil Halterung Zusammenbau');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0055/A', '3D Drucker');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0098/A', '0098', 'Netzteil-Halterung');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0098/A', 'B0055/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0055/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0055/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0055/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0055/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0055/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0055/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0082/A', '0082', 'Kabelbinder Netzteil');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0082/A', 'B0055/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0082/A', 'B0055/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0023/A', '0023', 'Netzteil 230V MPS-400');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0023/A', 'B0055/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0208/A', '0208', 'AC Power outlet connector');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0208/A', 'B0023/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0210/A', '0210', 'Einschalter');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0210/A', 'B0023/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0209/A', '0209', 'Luefter Netzteil');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0209/A', 'B0023/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0207/A', '0207', 'Netzteil Gehaeuse');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0207/A', 'B0023/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0056/A', '0056', 'Kabelabdeckung Zusammenbau');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0056/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0056/A', '3D Drucker');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0056/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0056/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0056/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0080/A', '0080', 'Kabelabdeckung');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0080/A', 'B0056/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0056/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0056/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0056/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0058/A', '0058', 'Mikrocontroller Halterung Zusammenbau');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0058/A', '3D Drucker');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0074/A', 'B0058/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0074/A', 'B0058/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0074/A', 'B0058/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0058/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0058/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0058/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0091/A', '0091', 'Mikrocontroller Halterung');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0091/A', 'B0058/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0058/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0058/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0058/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0058/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0058/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0058/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0057/A', '0057', 'Arduino Mega 2560 + Ramps 1.4 Zusammenbau');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0057/A', 'B0058/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0021/A', '0021', 'Ramps 1.4 inkl. Pololu Stepper Driver A4988');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0021/A', 'B0057/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0188/A', '0188', 'G3D_A4988');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('Teil_0188/A', 'B0021/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('Teil_0188/A', 'B0021/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('Teil_0188/A', 'B0021/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('Teil_0188/A', 'B0021/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('Teil_0188/A', 'B0021/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0175/A', '0175', 'Heat_Sink');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0175/A', 'Teil_0188/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0196/A', '0196', 'PCB');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0196/A', 'Teil_0188/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0170/A', '0170', 'SIL_Male_8Pin');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0170/A', 'Teil_0188/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0170/A', 'Teil_0188/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0193/A', '0193', 'microchip_28');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0193/A', 'Teil_0188/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0186/A', '0186', 'RAMPS1_4');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('Teil_0186/A', 'B0021/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0197/A', '0197', 'pin_header_aw254-dg-g06d');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0197/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0197/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0197/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0197/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0197/A', 'Teil_0186/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0189/A', '0189', 'pin_header_aw140-eg-g08d');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0189/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0189/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0189/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0189/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0189/A', 'Teil_0186/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0174/A', '0174', 'MF-R1100___ _________');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0174/A', 'Teil_0186/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0195/A', '0195', 'female_header_a-bl254-eg-g08d');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0195/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0195/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0195/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0195/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0195/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0195/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0195/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0195/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0195/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0195/A', 'Teil_0186/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0203/B', '0203', 'Teil_0203');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('Teil_0203/B', 'Teil_0186/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('Teil_0203/B', 'Teil_0186/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('Teil_0203/B', 'Teil_0186/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('Teil_0203/B', 'Teil_0186/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('Teil_0203/B', 'Teil_0186/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('Teil_0203/B', 'Teil_0186/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0184/A', '0184', 'CAPSMD6_3x3_9_CAP');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0184/A', 'Teil_0203/B');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0198/A', '0198', 'CAPSMD6_3x3_9_CAP001');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0198/A', 'Teil_0203/B');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0199/A', '0199', 'CAPSMD6_3x3_9_CAP002');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0199/A', 'Teil_0203/B');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0201/B', '0201', 'Teil_0201');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0201/B', 'Teil_0203/B');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0200/A', '0200', 'CAPSMD6_3x3_9_CAP003');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0200/A', 'Teil_0203/B');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0185/A', '0185', 'pin_header_aw140-eg-g04d');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0185/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0185/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0185/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0185/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0185/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0185/A', 'Teil_0186/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0169/A', '0169', 'pin_header_aw140-eg-g18d');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0169/A', 'Teil_0186/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0194/A', '0194', 'CAPSMD4x3_9');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('Teil_0194/A', 'Teil_0186/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('Teil_0194/A', 'Teil_0186/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('Teil_0194/A', 'Teil_0186/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0182/A', '0182', 'CAPSMD4x3_9_CAPSMD4x3_9004');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0182/A', 'Teil_0194/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0180/A', '0180', 'CAPSMD4x3_9_CAPSMD4x3_9002');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0180/A', 'Teil_0194/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0179/A', '0179', 'CAPSMD4x3_9_CAPSMD4x3_9001');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0179/A', 'Teil_0194/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0192/A', '0192', 'CAPSMD4x3_9_CAPSMD4x3_9');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0192/A', 'Teil_0194/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0181/A', '0181', 'CAPSMD4x3_9_CAPSMD4x3_9003');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0181/A', 'Teil_0194/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0191/A', '0191', 'terminal_blocks_a-tb508-oq04ch');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0191/A', 'Teil_0186/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0187/A', '0187', 'pin_header_aw140-eg-g06d');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0187/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0187/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0187/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0187/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0187/A', 'Teil_0186/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0190/A', '0190', 'MF-R500___ _________');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0190/A', 'Teil_0186/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0173/A', '0173', 'RAMPS1_4_1');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0173/A', 'Teil_0186/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0166/A', '0166', 'pin_header_aw254-dg-g08d');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0166/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0166/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0166/A', 'Teil_0186/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0176/A', '0176', 'SWITCH, TACTILE, RIGHT ANGLE, 12VDC, 50MA, 6_85MM ACTUATOR, WEALTH METAL TC-0244Z');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0176/A', 'Teil_0186/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0202/B', '0202', 'Teil_0202');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0202/B', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0202/B', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0202/B', 'Teil_0186/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0171/A', '0171', 'APA3010GCCK_GREEN');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0171/A', 'Teil_0186/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0177/A', '0177', 'pin_header_aw140-eg-g02d');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0177/A', 'Teil_0186/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0178/A', '0178', 'APA3010GCCK_RED');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0178/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0178/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0178/A', 'Teil_0186/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0183/A', '0183', 'pin_header_aw140-eg-g03d');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0183/A', 'Teil_0186/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0167/A', '0167', 'pin_header_aw254-dg-g10d');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0167/A', 'Teil_0186/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0172/A', '0172', 'pin_header_aw254-dg-g36d');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0172/A', 'Teil_0186/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0168/A', '0168', 'terminal_blocks_a-tb500-to06');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0168/A', 'Teil_0186/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0166/A', 'B0021/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0020/A', '0020', 'Arduino Mega 2560');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0020/A', 'B0057/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0131/A', '0131', 'BOURNS_MF-MSMF050-224');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0131/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0139/A', '0139', 'CAPC1608x08H4079');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0139/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0139/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0139/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0139/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0139/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0139/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0139/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0139/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0139/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0139/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0139/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0139/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0139/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0139/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0139/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0152/A', '0152', 'FAIRCHILD_FDN340P_Varsay__lan6960');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0152/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0135/A', '0135', 'RESC1608x55H12018');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0135/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0135/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0135/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0135/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0135/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0135/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0155/A', '0155', 'ATMEGA16U2-MUR_Varsay__lan13227');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0155/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0140/A', '0140', 'SAMTEC_SSQ-108-01-G-S_Varsay__lan47194');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0140/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0140/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0140/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0140/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0140/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0165/A', '0165', 'DI_S1BB-13_Varsay__lan58524');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0165/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0156/A', '0156', 'TE_FSM1LPATR_Varsay__lan67891');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0156/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0159/A', '0159', 'LUMEX_SML-LXT0805GW-TR_Varsay__lan72273');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0159/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0144/A', '0144', 'PANASONIC_EEE-1EA470WP_Varsay__lan75625');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0144/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0144/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0138/A', '0138', 'ON_NCP1117ST50T3G_Varsay__lan82402');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0138/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0142/A', '0142', 'LUMEX_SML-LXT0805SYW-TR_Varsay__lan90789');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0142/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0142/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0142/A', 'B0020/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0141/A', '0141', 'ARDUINO_MEGA2560_REF_PCB_Varsay__lan94120');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('Teil_0141/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0148/A', '0148', 'ARDUINO_MEGA2560_REF_PCB_BOTTOM_OVERLAY_Varsay__lan94128');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0148/A', 'Teil_0141/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0145/A', '0145', 'ARDUINO_MEGA2560_REF_PCB_BOTTOM_SOLDER_Varsay__lan192242');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0145/A', 'Teil_0141/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0158/A', '0158', 'ARDUINO_MEGA2560_REF_PCB_TOP_OVERLAY_Varsay__lan216337');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0158/A', 'Teil_0141/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0157/A', '0157', 'ARDUINO_MEGA2560_REF_PCB_BOTTOM_LAYER_Varsay__lan437426');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0157/A', 'Teil_0141/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0160/A', '0160', 'ARDUINO_MEGA2560_REF_PCB_MECHANICAL_Varsay__lan610049');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0160/A', 'Teil_0141/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0143/A', '0143', 'ARDUINO_MEGA2560_REF_PCB_TOP_SOLDER_Varsay__lan633196');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0143/A', 'Teil_0141/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0134/A', '0134', 'ARDUINO_MEGA2560_REF_PCB_ML_Varsay__lan705008');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0134/A', 'Teil_0141/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0133/A', '0133', 'ARDUINO_MEGA2560_REF_PCB_TOP_LAYER_Varsay__lan746915');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0133/A', 'Teil_0141/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0149/A', '0149', 'YAGEO_TC164-JR-0710KL_Varsay__lan1045031');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0149/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0149/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0164/A', '0164', 'SAMTEC_SSQ-106-01-G-S_Varsay__lan1053947');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0164/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0136/A', '0136', 'MOLEX_0010897061_Varsay__lan1062431');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0136/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0136/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0147/A', '0147', 'ATMEGA2560-16AUR_Varsay__lan1069171');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0147/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0132/A', '0132', 'LMV358IDGKR_Varsay__lan1129524');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0132/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0130/A', '0130', 'WURTH_61400416121_Varsay__lan1138352');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0130/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0161/A', '0161', 'CUI_PJ-102A1165735');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0161/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0153/A', '0153', 'TI_LP2985-33DBVR_Varsay__lan1170195');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0153/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0154/A', '0154', 'INDC2012x10H1175883');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0154/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0146/A', '0146', 'MURATA_CSTCE16M0V53-R0_Varsay__lan1177340');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0146/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0163/A', '0163', 'YAGEO_TC164-JR-071KL_Varsay__lan1180157');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0163/A', 'B0020/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0163/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0150/A', '0150', 'ABRACON_ABL-16.000MHZ-B2_Varsay__lan1188778');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0150/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0137/A', '0137', 'YAGEO_TC164-JR-0722RL_Varsay__lan1197654');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0137/A', 'B0020/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0162/A', '0162', 'SAMTEC_SSQ-118-01-G-D_Varsay__lan1206538');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0162/A', 'B0020/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0059/A', '0059', 'Luefter Halterung Zusammenbau');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0059/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0059/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0059/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0088/A', '0088', 'Elektronik-Luefter Halterung');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0088/A', 'B0059/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0059/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0059/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0059/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0059/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0059/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0059/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0049/A', 'B0059/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0049/A', 'B0059/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0024/A', '0024', 'Luefter_60x60x25mm');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0024/A', 'B0059/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0211/A', '0211', 'ventola_1');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0211/A', 'B0024/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0212/A', '0212', 'ventola_2');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0212/A', 'B0024/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0060/A', '0060', 'Endstophalter Zusammenbau');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0060/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0060/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0060/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0060/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0060/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0060/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0022/A', '0022', 'Optischer Endstopschalter');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0022/A', 'B0060/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0206/A', '0206', 'TCST2103 Endstop_Opto_TCST2103');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0206/A', 'B0022/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0205/A', '0205', 'PCB Endstop_Opto_TCST2103');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0205/A', 'B0022/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0204/A', '0204', 'Connector Endstop_Opto_TCST2103');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0204/A', 'B0022/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0057/A', '0057', 'Endstophalter');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0057/A', 'B0060/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0049/A', 'B0060/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0049/A', 'B0060/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0049/A', 'B0060/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0063/A', '0063', 'Luefter Halterung X-Achse Zusammenbau');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0063/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0044/A', 'B0063/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0044/A', 'B0063/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0063/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0063/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0024/A', 'B0063/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0087/A', '0087', 'Luefter Halterung X-Achse');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0087/A', 'B0063/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0063/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0061/A', '0061', 'Extruder Zusammenbau');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0061/A', '3D Drucker');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0097/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0072/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0072/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0072/A', 'B0061/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0043/A', 'B0061/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0043/A', 'B0061/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0043/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0119/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0119/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0105/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0105/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0105/A', 'B0061/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0062/A', '0062', 'Feder Extruder Innendurchmesser 5,3mm x 20mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0062/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0062/A', 'B0061/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0059/A', '0059', 'Extruder Idler');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0059/A', 'B0061/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0058/A', '0058', 'Extruder Body');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0058/A', 'B0061/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0112/A', '0112', 'Stange 8mm x 20mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0112/A', 'B0061/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0108/A', '0108', 'Sechskantmutter M4');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0108/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0108/A', 'B0061/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0025/A', '0025', 'J-Head Nozzle');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0025/A', 'B0061/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0213/A', '0213', 'JHead_Nozzle Part1');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0213/A', 'B0025/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0214/A', '0214', 'JHead_Nozzle Part2');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0214/A', 'B0025/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0123/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0123/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0123/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0123/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0123/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0123/A', 'B0061/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0061/A', '0061', 'Extruder Zahnrad klein');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0061/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0110/A', 'B0061/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0062/A', '0062', 'ISK-Schraube M3x50mm und Scheibe');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0062/A', 'B0061/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0062/A', 'B0061/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0119/A', 'B0062/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0077/A', '0077', 'Innensechskantschraube M3x50mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0077/A', 'B0062/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0064/A', '0064', 'Filamentschraube M8x50mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0064/A', 'B0061/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0060/A', '0060', 'Extruder Zahnrad gross');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0060/A', 'B0061/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0217/A', '0217', 'Filamentrollenhalter Klemmverschluss');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0217/A', '3D Drucker');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0216/A', '0216', 'Filamentrollenhalter Bolzen');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0216/A', '3D Drucker');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0064/A', '0064', 'Filamentrollenhalter Zusammenbau');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0064/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0064/A', '3D Drucker');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0064/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0079/A', 'B0064/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0215/A', '0215', 'Filamentrollenhalter Winkel');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0215/A', 'B0064/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0067/A', '0067', 'Justierbarer Z-Endstop Zusammenbau');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0067/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0022/A', 'B0067/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0065/A', '0065', 'Justierbarer Endstophalter Zusammenbau');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0065/A', 'B0067/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0065/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0065/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0065/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0065/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0065/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0107/A', 'B0065/A');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0066/A', '0066', 'Flachkopfschraube Schlitz M3x30mm mit Scheibe');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0066/A', 'B0065/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0066/A', 'B0065/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0119/A', 'B0066/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0220/A', '0220', 'Flachkopfschraube Schlitz M3x30mm');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0220/A', 'B0066/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0219/A', '0219', 'Justierbarer Endstophalter Platinenhalterung');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0219/A', 'B0065/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0218/A', '0218', 'Justierbarer Enstophalter Klemmteil');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0218/A', 'B0065/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0065/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0065/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0043/A', 'B0065/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0043/A', 'B0065/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0043/A', 'B0067/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0043/A', 'B0067/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0067/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0045/A', 'B0067/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0221/A', '0221', 'Blechfaehnchen Z-Achse justierbarer Endstop');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0221/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0043/A', '3D Drucker');
INSERT INTO Baugruppen (Baugruppennummer, Artikelnummer, Bezeichnung) VALUES ('B0068/A', '0068', 'Motorhalter Y-Achse Ausfuehrung 2 Zusammenbau');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0068/A', '3D Drucker');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0034/A', 'B0068/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0034/A', 'B0068/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0034/A', 'B0068/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0034/A', 'B0068/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0068/A');
INSERT INTO BaugruppenEinbau (Unterbaugruppe, Überbaugruppe) VALUES ('B0028/A', 'B0068/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0096/A', 'B0068/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0097/A', 'B0068/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0068/A');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0099/A', 'B0068/A');
INSERT INTO Teile (Teilnummer, Artikelnummer, Bezeichnung) VALUES ('Teil_0222/A', '0222', 'Motorhalter Y-Achse Ausfuehrung 2');
INSERT INTO TeileEinbau (Teil, Baugruppe) VALUES ('Teil_0222/A', 'B0068/A');


INSERT INTO Fertigungsdaten (Artikelnummer, Bearbeitungsdauer)
VALUES 
  ('0035', 123), ('0043', 23), ('0103', 500), ('0130', 341), ('0133', 845), ('0160', 34), ('0188', 9), ('0022', 50), ('0025', 10933), ('0030', 894), 
  ('0035', 150), ('0043', 24), ('0103', 505), ('0130', 340), ('0133', 850), ('0160', 32), ('0188', 10), ('0022', 51), ('0025', 11001), ('0030', 902),
  ('0035', 130), ('0043', 23), ('0103', 500), ('0130', 342), ('0133', 840), ('0160', 34), ('0188', 8), ('0022', 52), ('0025', 10901), ('0030', 891), 
  ('0035', 105), ('0043', 23), ('0103', 501), ('0130', 340), ('0133', 843), ('0160', 34), ('0188', 9), ('0022', 53), ('0025', 10980), ('0030', 899), 
  ('0035', 180), ('0043', 25), ('0103', 497), ('0130', 341), ('0133', 851), ('0160', 32), ('0188', 8), ('0022', 54), ('0025', 10979), ('0030', 898), 
  ('0035', 145), ('0043', 23), ('0103', 502), ('0130', 339), ('0133', 848), ('0160', 34), ('0188', 9), ('0022', 50), ('0025', 10945), ('0030', 882), 
  ('0035', 124), ('0043', 22), ('0103', 492), ('0130', 348), ('0133', 847), ('0160', 32), ('0188', 10), ('0022', 51), ('0025', 10873), ('0030', 899);
  